# Project Information
site_name: Aqua Onboarding Portal
site_description: 'Your Guided Path to Success with Aqua Security.'
site_author: 'Aqua Security Software'
site_url: 'https://ps.aquasec.com'

# Repository
repo_name: 'selfserve-content'
repo_url: 'https://github.com/aqua-ps/selfserve-content'

# Configuration
theme:
  features:
    - header.autohide
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
  name: material
  logo: resources/logo_aqua_white.svg
  font:
    text: Inter
  favicon: resources/aqua-favicon-wht.png
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
edit_uri: ""

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AquaSecTeam
    - icon: fontawesome/solid/paper-plane
      link: mailto:services@aquasec.com

# Navigation
nav:
  - Overview: index.md
  - Introduction:
    - intro/index.md
  - The Guided Path:
    - path/index.md
  - Shift Left:
    - shiftleft/index.md
  - Shift Right:
    - shiftright/index.md
  - Useful Resources:
    - useful/index.md

# Extensions
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - mdx_truly_sane_lists
  - pymdownx.tabbed:
      alternate_style: true

plugins:
    - include-markdown
    - search
    - glightbox
    - mermaid2:
        arguments:
          theme: |
            ^(window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) ? 'dark' : 'light'        
extra_javascript:
    - resources/mermaid.min.js #https://unpkg.com/mermaid/dist/mermaid.min.js for reference
